// @ts-check
// AUTO-GENERATED by build-site.mjs — do not edit manually
import { defineConfig } from 'astro/config';
import preact from '@astrojs/preact';
import sitemap from '@astrojs/sitemap';
import fs from 'node:fs';

const posts = JSON.parse(fs.readFileSync('./src/data/posts.json', 'utf8'));
const postDates = Object.fromEntries(
  posts.map(p => ['/posts/' + p.slug + '/', p.dateModified])
);

export default defineConfig({
  site: 'https://coffeegearpicks.com',
  output: 'static',
  build: {
    format: 'preserve',
  },
  trailingSlash: 'never',
  integrations: [
    preact(),
    sitemap({
      serialize(item) {
        const pathname = new URL(item.url).pathname;
        const mod = postDates[pathname];
        if (mod) item.lastmod = new Date(mod);
        return item;
      },
    }),
  ],
  vite: {
    server: {
      allowedHosts: true,
    },
    preview: {
      allowedHosts: true,
    },
  },
});
