// @ts-check
// AUTO-GENERATED by build-site.mjs — do not edit manually
import { defineConfig } from 'astro/config';
import preact from '@astrojs/preact';

export default defineConfig({
  site: 'https://coffeegearpicks.com',
  output: 'static',
  build: {
    format: 'preserve',
  },
  trailingSlash: 'never',
  integrations: [preact()],
});
