// AUTO-GENERATED by build-site.mjs — do not edit manually
export const SITE = {
  name: 'Coffee Gear Lab',
  url: 'https://coffeegearpicks.com',
  gaId: 'G-3Q4RL7QGN4',
};

export const AMAZON_TAG = 'coffee-site-20';
export const DISCLOSURE_TEXT = 'Coffee Gear Lab may earn a commission from qualifying purchases made through links on this page. This does not change the price you pay.';

export const NAV_LINKS = [
  {
    "label": "Home",
    "href": "/"
  },
  {
    "label": "All Guides",
    "href": "/posts/"
  },
  {
    "label": "Espresso",
    "href": "/espresso/"
  },
  {
    "label": "Grinders",
    "href": "/grinders/"
  },
  {
    "label": "Brewers",
    "href": "/brewers/"
  }
];

export const publisher = {
  '@type': 'Organization' as const,
  name: SITE.name,
};

export function blogPosting(opts: {
  headline: string;
  description: string;
  slug: string;
  datePublished: string;
  dateModified: string;
  image?: string;
}) {
  return {
    '@type': 'BlogPosting',
    headline: opts.headline,
    description: opts.description,
    datePublished: opts.datePublished,
    dateModified: opts.dateModified,
    author: publisher,
    publisher,
    mainEntityOfPage: `${SITE.url}/posts/${opts.slug}.html`,
    ...(opts.image ? { image: opts.image } : {}),
  };
}
